services:
  app:
    build: .
    expose:
      - "8091" # 스프링부트 포트번호(도움말)

  nginx:
    image: nginx
    ports:
      - "80:80" # 외부 접속
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
